version: '3.8'

services:

  autenticacion:
    build:
      context: ../componente/autenticacion
      dockerfile: Dockerfile
    container_name: bk-crediya-autenticacion
    image: crediya/bk-crediya-autenticacion:0.0.1
    ports:
      - "8080:8080"
    environment:
      - CORS_ALLOWED-ORIGINS=http://localhost:4200,http://localhost:8080
      - ADAPTERS_R2DBC_HOST=localhost
      - ADAPTERS_R2DBC_PORT=5432
      - ADAPTERS_R2DBC_DATABASE=postgres
      - ADAPTERS_R2DBC_SCHEMA=crediya
      - ADAPTERS_R2DBC_USERNAME=postgres
      - ADAPTERS_R2DBC_PASSWORD=postgres
      - ADAPTERS_TRANSACTION_REACTIVE_ENABLED=true
      - JWT_TK_KEY=jWdLDCLzz51gKYlojoRF5dE0S1KgNP1rqj4Zaau6Rwg=
    networks:
      - crediya-network

  solicitudes:
    build:
      context: ../componente/solicitudes
      dockerfile: Dockerfile
    container_name: bk-crediya-solicitudes
    image: crediya/bk-crediya-solicitudes:0.0.1
    ports:
      - "8081:8081"
    environment:
      - CORS_ALLOWED-ORIGINS=http://localhost:4200,http://localhost:8080
      - ADAPTERS_R2DBC_HOST=localhost
      - ADAPTERS_R2DBC_PORT=5432
      - ADAPTERS_R2DBC_DATABASE=postgres
      - ADAPTERS_R2DBC_SCHEMA=crediya
      - ADAPTERS_R2DBC_USERNAME=postgres
      - ADAPTERS_R2DBC_PASSWORD=postgres
      - ADAPTERS_TRANSACTION_REACTIVE_ENABLED=true
      - ADAPTERS_RESTCONSUMER_TIMEOUT=5000
      - ADAPTERS_RESTCONSUMER_URL=http://autenticacion:8080
      - JWT_TK_KEY=jWdLDCLzz51gKYlojoRF5dE0S1KgNP1rqj4Zaau6Rwg=
    networks:
      - crediya-network

networks:
  crediya-network:
    driver: bridge
